image: ubuntu:latest

before_script:
  - apt-get -yq update
  - apt-get -yq install software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt-get -yq update
  - apt-get -yq install python-minimal python3.9 python-pip
  - pip install -r requirements.txt

stages:
  - Test

pytest:
  stage: Test
  script:
  - python -m pytest
