# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/

image: "python:3.9"
#commands to run in the Docker container before starting each job.

before_script:
  - python3 --version
  - pip3 install -r requirements.txt

# different stages in the pipeline
stages:
  - Test

# defines the testing stage
pytest:
  stage: Test
  script:
  - python -m pytest
