repos:
  - repo: local
    hooks:
      - id: black-check
        name: black-check
        files: \.py$
        stages: [commit]
        language: system
        entry: black --check
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        files: \.py$
        stages: [commit]
        language: system
        entry: flake8 
