repos:
- repo: local
  hooks:
    # Run the formatter.
    - id: ruff-format
      name: ruff-format
      description: "Run 'ruff format' for extremely fast Python formatting"
      entry: ruff format --force-exclude
      language: python
      types_or: [python, pyi, jupyter]
    # Run the linter.
    - id: ruff
      name: ruff
      description: "Run 'ruff' for extremely fast Python linting"
      entry: ruff check --force-exclude
      args: [ --fix ] # Enable lint fixes.
      language: python
      types_or: [python, pyi, jupyter]
