repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        args: [ "--profile", "black", "--filter-files" ]
        language: system
        entry: isort
  - repo: local
    hooks:
      - id: black
        name: black
        files: \.py$
        stages: [commit]
        language: system
        entry: black
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        files: \.py$
        stages: [commit]
        language: system
        entry: flake8 
