[warehouses.pg_warehouse]
db_type = "postgresql"
database = "warehouse"
user = "warehouse_user"
password = "warehouse_password"
host = "localhost"
port = 7654

[datasets.companies_house]
database = "pg_warehouse"
db_schema = "companieshouse"
db_table = "companies"
db_pk = "id"

[datasets.data_hub_companies]
database = "pg_warehouse"
db_schema = "dbt"
db_table = "data_hub__companies"
db_pk = "id"

[datasets.hmrc_exporters]
database = "pg_warehouse"
db_schema = "hmrc"
db_table = "trade__exporters"
db_pk = "id"

[datasets.export_wins]
database = "pg_warehouse"
db_schema = "dbt"
db_table = "export_wins__wins_dataset"
db_pk = "id"