name: Scan for Secrets with Trufflehog

on:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog directly
        run: |
          docker run --rm -v ${{ github.workspace }}:/repo \
            trufflesecurity/trufflehog:latest \
            git file:///repo \
            --since-commit main \
            --branch $(git branch --show-current) \
            --github-actions \
            --fail